Repository ManageIQ/manageiq-providers-cisco_intersight, pull requests merged in 2022-05, with the labels that each got.

#53 Fix Cisco Intersight connection
  app/models/manageiq/providers/cisco_intersight/manager_mixin.rb
Labels: bug

#52 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#54 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#42 Add support for physical server profiles
  app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/inventory/persister/definitions/physical_infra_collections.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/server_profile_assignment.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server_profile.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_CiscoIntersight_PhysicalInfraManager_Refresher/refresh/will_perform_a_full_refresh.yml
Labels: enhancement

#51 Add server profile operations' dialogs
  app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_server_center.rb
  app/javascript/components/server-profile-form.js
  app/javascript/components/server-profile-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/assign_server_profile_button.rb
  package.json
Labels: enhancement

#56 Fix yarn installation
  .gitignore
  .yarn/releases/yarn-3.0.2.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: bug

#57 Fix Network Port's port_status
  app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
Labels: bug

#58 Fix of the renamed features and handle exception while fetching server profiles
  app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_server_center.rb
  app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb
Labels: bug

#60 Provide default for display_name matching other provider patterns
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server_profile.rb
Labels: bug

#59 Redefine `since` in method poll
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/event_catcher/stream.rb
Labels: enhancement

#64 Add buttons for deploying and unassigning server profiles in physical servers view
  app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_servers_center.rb
Labels: enhancement
