Repository ManageIQ/manageiq-providers-cisco_intersight, pull requests merged in 2022-04, with the labels that each got.

#39 Enhance Inventory's features - follow-up
  app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/inventory/persister/definitions/physical_infra_collections.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
Labels: enhancement

#38 Add support for lifecycle operations
  app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_server_center.rb
  app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_servers_center.rb
  app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/lifecycle.rb
Labels: enhancement

#43 Collect decommissioned servers
  app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/ManageIQ_Providers_CiscoIntersight_PhysicalInfraManager_Refresher/refresh/will_perform_a_full_refresh.yml
Labels: enhancement

#47 Fix server-chassis relationship
  app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
Labels: bug

#49 Update power parsing
  app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
Labels: enhancement

#45 Refactor IntersightClient ApiClient usage
  app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/manager_mixin.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/lifecycle.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/power.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager_spec.rb
Labels: refactoring
