Repository ManageIQ/manageiq-providers-cisco_intersight, pull requests merged in 2022-07, with the labels that each got.

#70 Set minimum client version to a much faster and leaner 0.1.4
  manageiq-providers-cisco_intersight.gemspec
Labels: bug, performance, najdorf/yes?

#71 Removing Memoization
  app/models/manageiq/providers/cisco_intersight/manager_mixin.rb
Labels: bug, najdorf/yes?

#72 Bump minimum version of intersight_client to 0.1.5
  manageiq-providers-cisco_intersight.gemspec
Labels: dependencies, performance
