Repository ManageIQ/manageiq-providers-cisco_intersight, pull requests merged in 2024-02, with the labels that each got.

#105 Drop require_nested and include_concern
  app/models/manageiq/providers/cisco_intersight/inventory.rb
  app/models/manageiq/providers/cisco_intersight/inventory/collector.rb
  app/models/manageiq/providers/cisco_intersight/inventory/parser.rb
  app/models/manageiq/providers/cisco_intersight/inventory/persister.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/event_catcher.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/firmware_update_task.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/provision.rb
  app/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresh_worker.rb
Labels: rails7, technical debt

#106 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#107 Allow overriding the Cisco Intersight ApiClient scheme/host/verify_ssl for on-premise intersight controller
  app/models/manageiq/providers/cisco_intersight/manager_mixin.rb
  spec/models/manageiq/providers/cisco_intersight/physical_infra_manager_spec.rb
Labels: enhancement

#108 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
